# -*- coding: utf-8 -*-
"""OPEN_QA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6Hu1ThTRZEfx67zeKadeAMdVCgC7rBK
"""

import torch
from datasets import load_dataset
from transformers import BertTokenizer, BertForQuestionAnswering
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

dataset = load_dataset("squad")

# take small subset for speed
small_data = dataset["train"].select(range(200))

documents = list(set([item["context"] for item in small_data]))

vectorizer = TfidfVectorizer(max_features=5000)
doc_vectors = vectorizer.fit_transform(documents)

def retrieve(question, k=3):
    q_vec = vectorizer.transform([question])
    scores = cosine_similarity(q_vec, doc_vectors)[0]
    top_k_idx = scores.argsort()[-k:][::-1]
    return [documents[i] for i in top_k_idx]

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForQuestionAnswering.from_pretrained("bert-base-uncased")

train_inputs = []
start_positions = []
end_positions = []

for item in small_data:
    question = item["question"]
    context = item["context"]
    answer = item["answers"]["text"][0]
    answer_start = item["answers"]["answer_start"][0]

    encoding = tokenizer(
        question,
        context,
        truncation=True,
        padding="max_length",
        max_length=128,
        return_offsets_mapping=True,
        return_tensors="pt"
    )

    offsets = encoding["offset_mapping"][0]

    start_token = 0
    end_token = 0

    for idx, (start, end) in enumerate(offsets):
        if start <= answer_start < end:
            start_token = idx
        if start < answer_start + len(answer) <= end:
            end_token = idx

    train_inputs.append(encoding["input_ids"][0])
    start_positions.append(start_token)
    end_positions.append(end_token)

train_inputs = torch.stack(train_inputs)
start_positions = torch.tensor(start_positions)
end_positions = torch.tensor(end_positions)

optimizer = torch.optim.AdamW(model.parameters(), lr=3e-5)

model.train()

for epoch in range(5):  # small epochs for speed
    total_loss = 0

    for i in range(len(train_inputs)):
        optimizer.zero_grad()

        outputs = model(
            input_ids=train_inputs[i].unsqueeze(0),
            start_positions=start_positions[i].unsqueeze(0),
            end_positions=end_positions[i].unsqueeze(0)
        )

        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch}, Loss: {total_loss:.4f}")

def answer_question(question):
    passages = retrieve(question, k=3)

    best_answer = ""
    best_score = -1e9

    for context in passages:
        inputs = tokenizer(
            question,
            context,
            return_tensors="pt",
            truncation=True,
            padding=True
        )

        with torch.no_grad():
            outputs = model(**inputs)

        start_scores = outputs.start_logits
        end_scores = outputs.end_logits

        start_idx = torch.argmax(start_scores)
        end_idx = torch.argmax(end_scores) + 1

        tokens = inputs["input_ids"][0][start_idx:end_idx]
        answer = tokenizer.decode(tokens)

        score = start_scores[0][start_idx] + end_scores[0][end_idx-1]

        if score > best_score:
            best_score = score
            best_answer = answer

    return best_answer

print(answer_question("Who wrote the Declaration of Independence?"))

print(answer_question("What is the capital of France?"))

torch.save(model.state_dict(), "bert_qa_model.pt")
print("Model saved to bert_qa_model.pt")

